from __future__ import annotations

from pathlib import Path
from typing import Protocol

from winter_cli.modules.workspace.models import (
    DiffMode,
    FeatureWorktree,
    LocalFastForward,
    MergeMode,
    ProjectRepository,
    PullMode,
    RebaseOntoResult,
    RepoDiffResult,
    RepoMergeOutcome,
    RepoStatus,
    RepoStatusAndHistory,
    RepoSyncOutcome,
    ResetMode,
    StandaloneRepository,
    StandaloneRepoStatus,
    Workspace,
)


class IReadRepoRepository(Protocol):
    def get_workspace(
        self,
        root_path: Path,
        service_prefix: str,
        main_branch: str,
        base_port: int = 4000,
        ports_per_env: int = 20,
    ) -> Workspace: ...
    def get_worktree_status(self, worktree: FeatureWorktree) -> RepoStatus: ...
    def get_worktree_status_for_snapshot(self, worktree: FeatureWorktree) -> RepoStatus: ...
    def get_worktree_status_and_history(self, worktree: FeatureWorktree) -> RepoStatusAndHistory: ...
    def get_standalone_status(self, repo: StandaloneRepository) -> StandaloneRepoStatus: ...
    def get_standalone_detail(self, repo: StandaloneRepository) -> RepoStatusAndHistory: ...
    def get_project_status(self, repo: ProjectRepository) -> RepoStatus: ...
    def get_diff(self, worktree: FeatureWorktree, mode: DiffMode) -> RepoDiffResult: ...
    def get_ref_tip(self, worktree: FeatureWorktree, ref: str) -> str | None: ...
    def is_ancestor(self, worktree: FeatureWorktree, ancestor_ref: str, ref: str) -> bool: ...
    def fork_point(self, worktree: FeatureWorktree, lower_ref: str, upper_ref: str) -> str | None: ...
    def is_rebase_in_progress(self, worktree: FeatureWorktree) -> bool: ...


class IWriteRepoRepository(IReadRepoRepository, Protocol):
    def fetch(self, worktree: FeatureWorktree) -> None: ...
    def integrate(
        self,
        worktree: FeatureWorktree,
        target_ref: str,
        mode: PullMode,
        autostash: bool,
    ) -> RepoSyncOutcome: ...
    def merge_ref(
        self,
        worktree: FeatureWorktree,
        source_ref: str,
        mode: MergeMode,
        autostash: bool,
    ) -> RepoMergeOutcome: ...
    def merge_ref_standalone(
        self,
        repo: StandaloneRepository,
        source_ref: str,
        mode: MergeMode,
        autostash: bool,
    ) -> RepoMergeOutcome: ...
    def sync_ff_only(self, repo: ProjectRepository) -> int: ...
    def set_upstream(self, worktree: FeatureWorktree, remote_branch: str) -> None: ...
    def unset_upstream(self, worktree: FeatureWorktree) -> None: ...
    def get_worktree_upstream(self, worktree: FeatureWorktree) -> str | None: ...
    def get_worktree_push_branch(self, worktree: FeatureWorktree) -> str | None: ...
    def set_push_default(self, worktree: FeatureWorktree) -> None: ...
    def push(self, worktree: FeatureWorktree, feature_branch: str | None = None) -> int: ...
    def get_remote_branch_tip(self, worktree: FeatureWorktree, branch: str) -> str | None: ...
    def fast_forward_local_branch(
        self, repo: ProjectRepository, branch: str, pre_remote_tip: str
    ) -> LocalFastForward | None: ...
    def has_local_ref(self, worktree: FeatureWorktree, ref: str) -> bool: ...
    def is_worktree_dirty(self, worktree: FeatureWorktree) -> bool: ...
    def count_commits_not_in(self, worktree: FeatureWorktree, ref: str, from_ref: str = "HEAD") -> int: ...
    def get_active_branch_name(self, worktree: FeatureWorktree) -> str | None: ...
    def get_branch_upstream(self, worktree: FeatureWorktree, branch_name: str) -> str | None: ...
    def force_checkout_env_branch(self, worktree: FeatureWorktree, target_ref: str) -> None: ...
    def reset_to(self, worktree: FeatureWorktree, mode: ResetMode, target_ref: str) -> None: ...
    def list_untracked(self, worktree: FeatureWorktree) -> list[str]: ...
    def clean_untracked(self, worktree: FeatureWorktree) -> list[str]: ...
    def fetch_standalone(self, repo: StandaloneRepository) -> None: ...
    def integrate_standalone(
        self,
        repo: StandaloneRepository,
        mode: PullMode,
        autostash: bool,
    ) -> RepoSyncOutcome: ...
    def push_standalone(self, repo: StandaloneRepository) -> int: ...
    def integrate_standalone_to_ref(
        self,
        repo: StandaloneRepository,
        target_ref: str,
        mode: PullMode,
        autostash: bool,
    ) -> RepoSyncOutcome: ...
    def get_standalone_tracking_ahead(self, repo: StandaloneRepository) -> int: ...
    def get_standalone_upstream(self, repo: StandaloneRepository) -> str | None: ...
    def rebase_onto(self, worktree: FeatureWorktree, newbase: str, oldbase: str, branch: str) -> RebaseOntoResult: ...
