from __future__ import annotations

from collections.abc import Iterable
from pathlib import Path
from typing import Protocol


class IFilesystemReader(Protocol):
    """Read-only filesystem queries: predicates, listings, file contents."""

    def exists(self, path: Path) -> bool: ...
    def is_file(self, path: Path) -> bool: ...
    def is_dir(self, path: Path) -> bool: ...
    def is_symlink(self, path: Path) -> bool: ...
    def iterdir(self, path: Path) -> list[Path]: ...
    def read_text(self, path: Path) -> str: ...
    def read_bytes(self, path: Path) -> bytes: ...
    def readlink(self, path: Path) -> Path: ...
    def access_x_ok(self, path: Path) -> bool: ...


class IFilesystemWriter(IFilesystemReader, Protocol):
    """Read-write filesystem operations: mkdir, write/append, symlink, remove, chmod."""

    def mkdir(self, path: Path, parents: bool = False, exist_ok: bool = False) -> None: ...
    def write_text(self, path: Path, data: str) -> None: ...
    def append_lines(self, path: Path, lines: Iterable[str]) -> None: ...
    def symlink_to(self, link_path: Path, target: Path) -> None: ...
    def unlink(self, path: Path) -> None: ...
    def rmtree(self, path: Path) -> None: ...
    def chmod(self, path: Path, mode: int) -> None: ...
